-- MySQL Script generated by MySQL Workbench
-- 02/06/18 23:46:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myblog` DEFAULT CHARACTER SET utf8mb4 ;
USE `myblog` ;

-- -----------------------------------------------------
-- Table `myblog`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`user` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `password` VARCHAR(255) NULL COMMENT '密码',
  `createAt` DATETIME NULL COMMENT '创建时间',
  `lastLogin` DATETIME NULL COMMENT '上一次登录时间',
  `lastIp` VARCHAR(255) NULL COMMENT '上一次登录IP',
  `nickName` VARCHAR(45) NULL COMMENT '昵称',
  `email` VARCHAR(255) NULL COMMENT '邮箱',
  `status` TINYINT UNSIGNED NULL COMMENT '用户状态：0.正常 1.停用',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '博客类型 :\n技术\n随笔\n算法\n等\n',
  `cdate` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`blog` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `userId` BIGINT UNSIGNED NOT NULL COMMENT '作者编号',
  `title` VARCHAR(255) NULL,
  `summary` TEXT NULL COMMENT '摘要',
  `content` TEXT NULL COMMENT 'markdown格式的内容，用于重新编辑',
  `commentNum` INT UNSIGNED NULL COMMENT '评论数',
  `heartNum` INT UNSIGNED NULL COMMENT '点赞数',
  `readNum` INT UNSIGNED NULL COMMENT '阅读数',
  `publishTime` DATETIME NULL COMMENT '文章创建时间',
  `url` VARCHAR(255) NULL COMMENT '文章相对URL',
  `signature` VARCHAR(255) NULL COMMENT '文章哈希签名，防止出现重复文章',
  `categoryID` BIGINT UNSIGNED NULL COMMENT '文章类别ID',
  `lastUpdateTime` DATETIME NULL COMMENT '文章上次修改时间',
  `path` VARCHAR(255) NULL COMMENT '静态化的文件磁盘路径',
  `coverURL` VARCHAR(255) NULL COMMENT '封面图片',
  `type` INT NULL DEFAULT 0 COMMENT '\'博文类型，0表示普通博文，1表示富博文(带封面图片)\',',
  `status` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '博文状态，0显示，1不显示，2草稿',
  `statusName` VARCHAR(45) NULL COMMENT '状态名称：显示，不显示，草稿',
  `html` TEXT NULL COMMENT 'html格式的博文，主要用于重新静态化',
  `tags` VARCHAR(255) NULL COMMENT '博文标签',
  `shareNum` INT UNSIGNED NULL DEFAULT 0 COMMENT '分享次数',
  `type_id` BIGINT UNSIGNED NOT NULL COMMENT '文章类型',
  PRIMARY KEY (`id`),
  INDEX `fk_blog_user_idx` (`userId` ASC),
  INDEX `fk_blog_type1_idx` (`type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`tags` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '标签名称',
  `cdate` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myblog`.`blog_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`blog_tags` (
  `blogID` BIGINT UNSIGNED NOT NULL COMMENT '博客编号',
  `tagID` BIGINT UNSIGNED NOT NULL COMMENT '标签编号',
  PRIMARY KEY (`blogID`, `tagID`),
  INDEX `fk_blog_tags_blog1_idx` (`blogID` ASC),
  INDEX `fk_blog_tags_tags1_idx` (`tagID` ASC))
ENGINE = InnoDB
COMMENT = '文章和标签中间表';


-- -----------------------------------------------------
-- Table `myblog`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`category` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `cdate` DATETIME NULL,
  `keywords` VARCHAR(255) NULL,
  `blogNum` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = ' 类别';


-- -----------------------------------------------------
-- Table `myblog`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`comment` (
  `id` BIGINT UNSIGNED NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL COMMENT '用户名',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `content` TEXT NULL COMMENT '评论内容',
  `cdate` DATETIME NULL COMMENT '评论时间',
  `likeNum` INT NULL DEFAULT 0 COMMENT '喜欢次数',
  `hateNum` INT NULL DEFAULT 0,
  `parent` BIGINT NULL,
  `shareNum` INT NULL DEFAULT 0,
  `replyNum` INT NULL DEFAULT 0,
  `headURL` VARCHAR(255) NULL COMMENT '头像地址',
  `check` TINYINT NULL DEFAULT 0 COMMENT '是否审核，0表示未审核，1表示审核',
  `status` TINYINT NULL DEFAULT 1 COMMENT '\'是否合法，0未通过，1通过\'',
  `blogID` BIGINT UNSIGNED NOT NULL COMMENT '博客id',
  PRIMARY KEY (`id`),
  INDEX `fk_comment_blog1_idx` (`blogID` ASC))
ENGINE = InnoDB
COMMENT = '评论表';


-- -----------------------------------------------------
-- Table `myblog`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`notice` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NULL,
  `start` DATETIME NULL,
  `end` VARCHAR(45) NULL,
  `visible` TINYINT NULL DEFAULT 1 COMMENT '\'0,不可见，1可见\'',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '顶部的tips';


-- -----------------------------------------------------
-- Table `myblog`.`timeline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`timeline` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `createdDate` DATETIME NULL COMMENT '创建时间',
  `displayName` VARCHAR(45) NULL COMMENT '显示名称',
  `displayDate` VARCHAR(45) NULL COMMENT '显示日期',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '时间轴';


-- -----------------------------------------------------
-- Table `myblog`.`youlian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myblog`.`youlian` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL COMMENT '链接名称',
  `logo` VARCHAR(255) NULL COMMENT '链接图标',
  `url` VARCHAR(255) NULL COMMENT '地址',
  `cdate` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '友情链接';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
